on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

        # We're pinning the version to 1.4's RC candidate
        # Remove once released.
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.4.545

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.2"

      - name: Render sample deployment RevealJS presentation template
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: "index.qmd"

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
